on:
  push:
    branches:
      - master

name: Publish release on new master commit

jobs:
  build:
    name: Build & release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt 
      - name: Build project
        run: |
          python2 setup.py sdist --formats=gztar,zip
          python2 setup.py dist_info
      - name: Get version
        run: |
          ::set-env name=VERSION::`cat wsgiservice_restplus.dist-info/METADATA | grep "^Version" | sed -e "s/^Version: //"`
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset-zip 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./dist/wsgiservice_restplus-${{ env.VERSION }}.zip
          asset_name: wsgiservice_restplus-${{ env.VERSION }}.zip
          asset_content_type: application/zip
      - name: Upload Release Asset
        id: upload-release-asset-tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./dist/wsgiservice_restplus-${{ env.VERSION }}.tar.gz
          asset_name: wsgiservice_restplus-${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip
